package persistence;


import java.io.*;
import java.sql.*;
import java.util.*;
import java.math.*;

 /**
  * Registro_practica Value Object.
  * This class is value object representing database table registro_practica
  * This class is intented to be used together with associated Dao object.
  */

 /**
  * This sourcecode has been generated by FREE DaoGen generator version 2.4.1.
  * The usage of generated code is restricted to OpenSource software projects
  * only. DaoGen is available in http://titaniclinux.net/daogen/
  * It has been programmed by Tuomo Lukka, Tuomo.Lukka@iki.fi
  *
  * DaoGen license: The following DaoGen generated source code is licensed
  * under the terms of GNU GPL license. The full text for license is available
  * in GNU project's pages: http://www.gnu.org/copyleft/gpl.html
  *
  * If you wish to use the DaoGen generator to produce code for closed-source
  * commercial applications, you must pay the lisence fee. The price is
  * 5 USD or 5 Eur for each database table, you are generating code for.
  * (That includes unlimited amount of iterations with all supported languages
  * for each database table you are paying for.) Send mail to
  * "Tuomo.Lukka@iki.fi" for more information. Thank you!
  */



public class Registro_practica implements Cloneable, Serializable {

    /** 
     * Persistent Instance variables. This data is directly 
     * mapped to the columns of database table.
     */
    private int codigo_registro;
    private String codigo_practica;
    private String codigo_usuario;
    private String fecha;
    private String hora_inicio;
    private String hora_fin;



    /** 
     * Constructors. DaoGen generates two constructors by default.
     * The first one takes no arguments and provides the most simple
     * way to create object instance. The another one takes one
     * argument, which is the primary key of the corresponding table.
     */

    public Registro_practica () {

    }

    public Registro_practica (int codigo_registroIn) {

          this.codigo_registro = codigo_registroIn;

    }


    /** 
     * Get- and Set-methods for persistent variables. The default
     * behaviour does not make any checks against malformed data,
     * so these might require some manual additions.
     */

    public int getCodigo_registro() {
          return this.codigo_registro;
    }
    public void setCodigo_registro(int codigo_registroIn) {
          this.codigo_registro = codigo_registroIn;
    }

    public String getCodigo_practica() {
          return this.codigo_practica;
    }
    public void setCodigo_practica(String codigo_practicaIn) {
          this.codigo_practica = codigo_practicaIn;
    }

    public String getCodigo_usuario() {
          return this.codigo_usuario;
    }
    public void setCodigo_usuario(String codigo_usuarioIn) {
          this.codigo_usuario = codigo_usuarioIn;
    }

    public String getFecha() {
          return this.fecha;
    }
    public void setFecha(String fechaIn) {
          this.fecha = fechaIn;
    }

    public String getHora_inicio() {
          return this.hora_inicio;
    }
    public void setHora_inicio(String hora_inicioIn) {
          this.hora_inicio = hora_inicioIn;
    }

    public String getHora_fin() {
          return this.hora_fin;
    }
    public void setHora_fin(String hora_finIn) {
          this.hora_fin = hora_finIn;
    }



    /** 
     * setAll allows to set all persistent variables in one method call.
     * This is useful, when all data is available and it is needed to 
     * set the initial state of this object. Note that this method will
     * directly modify instance variales, without going trough the 
     * individual set-methods.
     */

    public void setAll(int codigo_registroIn,
          String codigo_practicaIn,
          String codigo_usuarioIn,
          String fechaIn,
          String hora_inicioIn,
          String hora_finIn) {
          this.codigo_registro = codigo_registroIn;
          this.codigo_practica = codigo_practicaIn;
          this.codigo_usuario = codigo_usuarioIn;
          this.fecha = fechaIn;
          this.hora_inicio = hora_inicioIn;
          this.hora_fin = hora_finIn;
    }


    /** 
     * hasEqualMapping-method will compare two Registro_practica instances
     * and return true if they contain same values in all persistent instance 
     * variables. If hasEqualMapping returns true, it does not mean the objects
     * are the same instance. However it does mean that in that moment, they 
     * are mapped to the same row in database.
     */
    public boolean hasEqualMapping(Registro_practica valueObject) {

          if (valueObject.getCodigo_registro() != this.codigo_registro) {
                    return(false);
          }
          if (this.codigo_practica == null) {
                    if (valueObject.getCodigo_practica() != null)
                           return(false);
          } else if (!this.codigo_practica.equals(valueObject.getCodigo_practica())) {
                    return(false);
          }
          if (this.codigo_usuario == null) {
                    if (valueObject.getCodigo_usuario() != null)
                           return(false);
          } else if (!this.codigo_usuario.equals(valueObject.getCodigo_usuario())) {
                    return(false);
          }
          if (this.fecha == null) {
                    if (valueObject.getFecha() != null)
                           return(false);
          } else if (!this.fecha.equals(valueObject.getFecha())) {
                    return(false);
          }
          if (this.hora_inicio == null) {
                    if (valueObject.getHora_inicio() != null)
                           return(false);
          } else if (!this.hora_inicio.equals(valueObject.getHora_inicio())) {
                    return(false);
          }
          if (this.hora_fin == null) {
                    if (valueObject.getHora_fin() != null)
                           return(false);
          } else if (!this.hora_fin.equals(valueObject.getHora_fin())) {
                    return(false);
          }

          return true;
    }



    /**
     * toString will return String object representing the state of this 
     * valueObject. This is useful during application development, and 
     * possibly when application is writing object states in textlog.
     */
    public String toString() {
        StringBuffer out = new StringBuffer(this.getDaogenVersion());
        out.append("\nclass Registro_practica, mapping to table registro_practica\n");
        out.append("Persistent attributes: \n"); 
        out.append("codigo_registro = " + this.codigo_registro + "\n"); 
        out.append("codigo_practica = " + this.codigo_practica + "\n"); 
        out.append("codigo_usuario = " + this.codigo_usuario + "\n"); 
        out.append("fecha = " + this.fecha + "\n"); 
        out.append("hora_inicio = " + this.hora_inicio + "\n"); 
        out.append("hora_fin = " + this.hora_fin + "\n"); 
        return out.toString();
    }


    /**
     * Clone will return identical deep copy of this valueObject.
     * Note, that this method is different than the clone() which
     * is defined in java.lang.Object. Here, the retuned cloned object
     * will also have all its attributes cloned.
     */
    public Object clone() {
        Registro_practica cloned = new Registro_practica();

        cloned.setCodigo_registro(this.codigo_registro); 
        if (this.codigo_practica != null)
             cloned.setCodigo_practica(new String(this.codigo_practica)); 
        if (this.codigo_usuario != null)
             cloned.setCodigo_usuario(new String(this.codigo_usuario)); 
        if (this.fecha != null)
             cloned.setFecha(new String(this.fecha)); 
        if (this.hora_inicio != null)
             cloned.setHora_inicio(new String(this.hora_inicio)); 
        if (this.hora_fin != null)
             cloned.setHora_fin(new String(this.hora_fin)); 
        return cloned;
    }



    /** 
     * getDaogenVersion will return information about
     * generator which created these sources.
     */
    public String getDaogenVersion() {
        return "DaoGen version 2.4.1";
    }

}
