package persistence;


import java.io.*;
import java.sql.*;
import java.util.*;
import java.math.*;

 /**
  * Practica Value Object.
  * This class is value object representing database table practica
  * This class is intented to be used together with associated Dao object.
  */

 /**
  * This sourcecode has been generated by FREE DaoGen generator version 2.4.1.
  * The usage of generated code is restricted to OpenSource software projects
  * only. DaoGen is available in http://titaniclinux.net/daogen/
  * It has been programmed by Tuomo Lukka, Tuomo.Lukka@iki.fi
  *
  * DaoGen license: The following DaoGen generated source code is licensed
  * under the terms of GNU GPL license. The full text for license is available
  * in GNU project's pages: http://www.gnu.org/copyleft/gpl.html
  *
  * If you wish to use the DaoGen generator to produce code for closed-source
  * commercial applications, you must pay the lisence fee. The price is
  * 5 USD or 5 Eur for each database table, you are generating code for.
  * (That includes unlimited amount of iterations with all supported languages
  * for each database table you are paying for.) Send mail to
  * "Tuomo.Lukka@iki.fi" for more information. Thank you!
  */



public class Practica implements Cloneable, Serializable {

    /** 
     * Persistent Instance variables. This data is directly 
     * mapped to the columns of database table.
     */
    private int codigo_practica;
    private String serie;
    private String titulo;
    private String descripcion;



    /** 
     * Constructors. DaoGen generates two constructors by default.
     * The first one takes no arguments and provides the most simple
     * way to create object instance. The another one takes one
     * argument, which is the primary key of the corresponding table.
     */

    public Practica () {

    }

    public Practica (int codigo_practicaIn) {

          this.codigo_practica = codigo_practicaIn;

    }


    /** 
     * Get- and Set-methods for persistent variables. The default
     * behaviour does not make any checks against malformed data,
     * so these might require some manual additions.
     */

    public int getCodigo_practica() {
          return this.codigo_practica;
    }
    public void setCodigo_practica(int codigo_practicaIn) {
          this.codigo_practica = codigo_practicaIn;
    }

    public String getSerie() {
          return this.serie;
    }
    public void setSerie(String serieIn) {
          this.serie = serieIn;
    }

    public String getTitulo() {
          return this.titulo;
    }
    public void setTitulo(String tituloIn) {
          this.titulo = tituloIn;
    }

    public String getDescripcion() {
          return this.descripcion;
    }
    public void setDescripcion(String descripcionIn) {
          this.descripcion = descripcionIn;
    }



    /** 
     * setAll allows to set all persistent variables in one method call.
     * This is useful, when all data is available and it is needed to 
     * set the initial state of this object. Note that this method will
     * directly modify instance variales, without going trough the 
     * individual set-methods.
     */

    public void setAll(int codigo_practicaIn,
          String serieIn,
          String tituloIn,
          String descripcionIn) {
          this.codigo_practica = codigo_practicaIn;
          this.serie = serieIn;
          this.titulo = tituloIn;
          this.descripcion = descripcionIn;
    }


    /** 
     * hasEqualMapping-method will compare two Practica instances
     * and return true if they contain same values in all persistent instance 
     * variables. If hasEqualMapping returns true, it does not mean the objects
     * are the same instance. However it does mean that in that moment, they 
     * are mapped to the same row in database.
     */
    public boolean hasEqualMapping(Practica valueObject) {

          if (valueObject.getCodigo_practica() != this.codigo_practica) {
                    return(false);
          }
          if (this.serie == null) {
                    if (valueObject.getSerie() != null)
                           return(false);
          } else if (!this.serie.equals(valueObject.getSerie())) {
                    return(false);
          }
          if (this.titulo == null) {
                    if (valueObject.getTitulo() != null)
                           return(false);
          } else if (!this.titulo.equals(valueObject.getTitulo())) {
                    return(false);
          }
          if (this.descripcion == null) {
                    if (valueObject.getDescripcion() != null)
                           return(false);
          } else if (!this.descripcion.equals(valueObject.getDescripcion())) {
                    return(false);
          }

          return true;
    }



    /**
     * toString will return String object representing the state of this 
     * valueObject. This is useful during application development, and 
     * possibly when application is writing object states in textlog.
     */
    public String toString() {
        StringBuffer out = new StringBuffer(this.getDaogenVersion());
        out.append("\nclass Practica, mapping to table practica\n");
        out.append("Persistent attributes: \n"); 
        out.append("codigo_practica = " + this.codigo_practica + "\n"); 
        out.append("serie = " + this.serie + "\n"); 
        out.append("titulo = " + this.titulo + "\n"); 
        out.append("descripcion = " + this.descripcion + "\n"); 
        return out.toString();
    }


    /**
     * Clone will return identical deep copy of this valueObject.
     * Note, that this method is different than the clone() which
     * is defined in java.lang.Object. Here, the retuned cloned object
     * will also have all its attributes cloned.
     */
    public Object clone() {
        Practica cloned = new Practica();

        cloned.setCodigo_practica(this.codigo_practica); 
        if (this.serie != null)
             cloned.setSerie(new String(this.serie)); 
        if (this.titulo != null)
             cloned.setTitulo(new String(this.titulo)); 
        if (this.descripcion != null)
             cloned.setDescripcion(new String(this.descripcion)); 
        return cloned;
    }



    /** 
     * getDaogenVersion will return information about
     * generator which created these sources.
     */
    public String getDaogenVersion() {
        return "DaoGen version 2.4.1";
    }

}
